### ISSUE TITLE
Enable searching only block-enabled plugins in plugins directory

### ISSUE THREAD

**Issue by Lovor01** [WordPress/wordpress.org#334] opened 2024-06-22 13:56 UTC
There is a URL dedicated to block-enabled plugins:
https://wordpress.org/plugins/browse/block/

On that page, only block enabled plugins are filtered. There is a search box on the top. When one enters a term in that box, all plugins that fit search results come out as a results. I would expect that this search box works only on block enabled plugins subset.

To my knoledge, currently there is no way to search only block enabled plugins in directory. I propose to introduce that possibility. This would give greater visibility of blocks from which to choose to users, simliarly to block search inside block editor.

**Comment by dd32** [comment] 2024-06-24 02:48
This would fall under https://meta.trac.wordpress.org/ticket/2753  with a filter such as `has blocks` or `in block directory`.

I'm going to mark this as a duplicate of the above ticket to keep discussion in the same place.

**Closed as not planned** 2024-06-24 02:48 UTC
